baseURL = "https://heroic-sunflower-159eb0.netlify.app/"
languageCode = "en-us"
title = "Backbone Communication"
theme = "four"
googleAnalytics = "UA-PROPERTY_ID/G-MEASUREMENT_ID"
disqusShortname = "yourdiscussshortname"

[params]
description = "Open Graph Description"
images = [ "/img/hero1.webp" ]
title = "Four: Travel Blog"
favicon = "img/world-map-pin.svg"

  [[params.values]]
  iconclass = "fas fa-pen text-primary fa-3x py-3"
  title = "Blog"
  description = "Dedicated to sharing insightful information"

  [[params.values]]
  iconclass = "fas fa-bolt text-primary fa-3x py-3"
  title = "Speed"
  description = "Our priority in getting the job done fast"

  [[params.values]]
  iconclass = "fas fa-comment text-primary fa-3x py-3"
  title = "Chat"
  description = "Keep in touch with us to know more"

[minify]
minifyOutput = true

[[menu.main]]
identifier = "HOME"
name = "home"
url = "/./"
weight = 1

[[menu.main]]
identifier = "ourservices"
name = "OUR SERVICES"
url = "/our-services"
weight = 2

[[menu.main]]
identifier = "news"
name = "NEWS"
url = "/news"
weight = 3

[[menu.main]]
identifier = "aboutus"
name = "ABOUT US"
url = "/about-us"
weight = 4

[[menu.main]]
identifier = "schoolsuccess"
name = "SCHOOL SUCCESS"
url = "/school-success"
weight = 5

[[menu.main]]
identifier = "events"
name = "EVENTS"
url = "/events"
weight = 6

[[menu.main]]
identifier = "contactus"
name = "CONTACT US"
url = "/contact-us"
weight = 6
[[menu.social]]
name = "fab fa-twitter fa-2x link-info"
title = "Twitter"
url = "/"
weight = 1

[[menu.social]]
name = "fab fa-youtube fa-2x link-danger"
title = "Youtube"
url = "/"
weight = 2
[params.logo]
    mobile = "/img/backbone_logo_dark.png"
    
